version: '3'
services:
  iris:
    image: containers.intersystems.com/intersystems/irishealth-community:2025.1
    init: true
    command:
      - -a
      - /home/irisowner/metadata/dev-init.sh
    working_dir: /home/irisowner/metadata
    ports:
      - 52773
    volumes:
      - .:/home/irisowner/metadata
